// Curated Pokémon pool for the first cut of vgc-dex, aimed at the
// Pokémon Champions Regulation M-C metagame (VGC Doubles, no Legendaries).
//
// This is intentionally a subset — it keeps `npm run build:data` fast and the
// bundled snapshot small. Add or remove entries freely and re-run the ETL;
// the app reads whatever `src/data/pokemon.json` contains.
//
// An entry is either a PokéAPI slug string, or an object:
//   { slug, display?, api? }
//     slug    — canonical id used everywhere in the app (and to match usage data)
//     display — nicer label when the auto-generated name is awkward
//     api     — the PokéAPI `/pokemon/<…>` slug to fetch, when it differs from
//               `slug` (species with only form-specific resources)

/** @type {(string | { slug: string, display?: string, api?: string })[]} */
export const REG_MC_POKEMON = [
  'garchomp',
  'dragonite',
  'gholdengo',
  'kingambit',
  'amoonguss',
  'rillaboom',
  'incineroar',
  'whimsicott',
  'dragapult',
  'gardevoir',
  'hydreigon',
  'tyranitar',
  'scizor',
  'metagross',
  'salamence',
  'gyarados',
  'milotic',
  'gastrodon',
  'arcanine',
  'talonflame',
  'corviknight',
  'grimmsnarl',
  'sylveon',
  'glimmora',
  'garganacl',
  'annihilape',
  { slug: 'maushold', display: 'Maushold', api: 'maushold-family-of-four' },
  'meowscarada',
  'skeledirge',
  'quaquaval',
  'baxcalibur',
  'tinkaton',
  { slug: 'mimikyu', display: 'Mimikyu', api: 'mimikyu-disguised' },
  'ceruledge',
  'armarouge',
  'dondozo',
  { slug: 'tatsugiri', display: 'Tatsugiri', api: 'tatsugiri-curly' },
  'breloom',
  'togekiss',
  'ferrothorn',
  'weavile',
  'mienshao',
  'porygon2',
  'sinistcha',
  'pelipper',
  'torkoal',
  'ursaluna',
  'kommo-o',
  'azumarill',
  'clefable',
  { slug: 'basculegion', display: 'Basculegion', api: 'basculegion-male' },
  { slug: 'indeedee', display: 'Indeedee', api: 'indeedee-male' },
  { slug: 'rotom-wash', display: 'Rotom-Wash' },
  { slug: 'rotom-heat', display: 'Rotom-Heat' },
  { slug: 'ninetales-alola', display: 'Alolan Ninetales' },
  { slug: 'lilligant-hisui', display: 'Hisuian Lilligant' },

  // Mega-capable classics (see scripts/build-megadex.mjs for the Mega forms).
  'charizard',
  'venusaur',
  'blastoise',
  'alakazam',
  'gengar',
  'kangaskhan',
  'pinsir',
  'aerodactyl',
  'ampharos',
  'steelix',
  'heracross',
  'houndoom',
  'sableye',
  'mawile',
  'aggron',
  'medicham',
  'manectric',
  'sharpedo',
  'camerupt',
  'altaria',
  'banette',
  'absol',
  'glalie',
  'lopunny',
  'lucario',
  'beedrill',
  'pidgeot',
  'slowbro',
  'abomasnow',

  // More common VGC picks.
  'excadrill',
  'magnezone',
  'chandelure',
  'conkeldurr',
  'volcarona',
  'staraptor',
  'hitmontop',
  'primarina',
  'hatterene',

  // Champions VGC 2026 ladder regulars (Showdown/Smogon usage ≳ 0.5%) not
  // covered above — keeps the reference pool in step with the usage ingest.
  'sneasler',
  'farigiraf',
  'archaludon',
  'arcanine-hisui',
  'politoed',
  'toxapex',
  'vivillon',
  'tsareena',
  { slug: 'lycanroc-dusk', display: 'Lycanroc-Dusk' },
  'mamoswine',
  'gallade',
  'samurott-hisui',
  'zoroark-hisui',
  'swampert',
  { slug: 'aegislash', display: 'Aegislash', api: 'aegislash-shield' },
  'vanilluxe',
  'mudsdale',
  { slug: 'palafin', display: 'Palafin', api: 'palafin-zero' },
  'typhlosion-hisui',
  'ninetales',
  'espathra',
  'snorlax',
  'araquanid',
  'overqwil',
  'oranguru',
  'blaziken',
  'kleavor',
  'bellibolt',
  'slowking-galar',
  'houndstone',
  'vileplume',

  // Base species whose Champions-VGC usage is driven by a Mega form (some of
  // which are Champions-original and not on PokéAPI — the base still gets a
  // usage panel; the Mega switcher only shows where megadex has the form).
  'raichu',
  'floette',
  'delphox',
  'froslass',
  'scovillain',
  { slug: 'pyroar', display: 'Pyroar', api: 'pyroar-male' },
  'scrafty',
  'meganium',
  'malamar',
  'greninja',
  'drampa',
  'audino',
  'sceptile',
]
